force-app/main/default/objects/DadosBancarios__c/DadosBancarios__c.object-meta.xml
<CustomObject>
    <label>Dados Bancários</label>
    <nameField>
        <displayFormat>DB-{0000}</displayFormat>
        <label>Nome de Dados Bancários</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dados Bancários</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DadosBancarios__c/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agência</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DadosBancarios__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bradesco</fullName>
            </value>
            <value>
                <fullName>Caixa Econômica Federal</fullName>
            </value>
            <value>
                <fullName>Itaú</fullName>
            </value>
            <value>
                <fullName>Santander</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DadosBancarios__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dados Bancários</relationshipLabel>
    <relationshipName>DadosBancarios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DadosBancarios__c/fields/NumeroConta__c.field-meta.xml
<CustomField>
    <fullName>NumeroConta__c</fullName>
    <label>Número da Conta</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DadosBancariosBOTest.cls
@isTest
private class DadosBancariosBOTest{
    @TestSetup
    static void dataSetup(){
        TestDataFactory.gerarConta();
        
    }

    @isTest
    static void insereDadosBancariosSucesso(){
        Account conta = [SELECT Id FROM Account LIMIT 1];

        User user = TestDataFactory.gerarUsuario(true, 'Custom: Sales Profile');
        DadosBancariosBO classDB = new DadosBancariosBO();

        System.runAs(user){
            Test.startTest();
                classDB.insereDadosBancarios(conta.Id,'Itaú',123,456);
            Test.stopTest();
        }

        DadosBancarios__c dbTest = [SELECT Conta__c, Banco__c, Agencia__c, NumeroConta__c FROM DadosBancarios__c WHERE Conta__c =: conta.Id];

        System.assertEquals(conta.Id, dbTest.Conta__c);
        System.assertEquals('Itaú', dbTest.Banco__c);
        System.assertEquals(123, dbTest.Agencia__c);
        System.assertEquals(456, dbTest.NumeroConta__c);
    }

    @isTest
    static void insereDadosBancariosBancoNaoExiste(){
        String messageError;
        Account conta = [SELECT Id FROM Account LIMIT 1];

        User user = TestDataFactory.gerarUsuario(true, 'Custom: Sales Profile');
        DadosBancariosBO classDB = new DadosBancariosBO();

        System.runAs(user){
            Test.startTest();
                try {
                    classDB.insereDadosBancarios(conta.Id,'Banco Falso',123,456);
                } catch (Exception e) {
                    messageError = e.getMessage();
                }
            Test.stopTest();
            System.assertEquals('Banco não disponível para inserção!', messageError);
        }
    }

    @isTest
    static void insereDadosBancariosBancoValorNumeroContaZero(){
        String messageError;
        Account conta = [SELECT Id FROM Account LIMIT 1];

        User user = TestDataFactory.gerarUsuario(true, 'Custom: Sales Profile');
        DadosBancariosBO classDB = new DadosBancariosBO();

        System.runAs(user){
            Test.startTest();
                try {
                    classDB.insereDadosBancarios(conta.Id,'Santander',0,456);
                } catch (Exception e) {
                    messageError = e.getMessage();
                }
            Test.stopTest();
            System.assertEquals('Agência e Número de Conta não podem ser igual a zero!', messageError);
        }
    }

    @isTest
    static void insereDadosBancariosBancoValorAgenciaZero(){
        String messageError;
        Account conta = [SELECT Id FROM Account LIMIT 1];

        User user = TestDataFactory.gerarUsuario(true, 'Custom: Sales Profile');
        DadosBancariosBO classDB = new DadosBancariosBO();

        System.runAs(user){
            Test.startTest();
                try {
                    classDB.insereDadosBancarios(conta.Id,'Santander',132,0);
                } catch (Exception e) {
                    messageError = e.getMessage();
                }
            Test.stopTest();
            System.assertEquals('Agência e Número de Conta não podem ser igual a zero!', messageError);
        }
    }
}