force-app/main/default/objects/DadosBancarios__c/DadosBancarios__c.object-meta.xml
<CustomObject>
    <label>Dados Bancários</label>
    <nameField>
        <displayFormat>DB-{0000}</displayFormat>
        <label>Nome de Dados Bancários</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dados Bancários</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DadosBancarios__c/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agência</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DadosBancarios__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bradesco</fullName>
            </value>
            <value>
                <fullName>Caixa Econômica Federal</fullName>
            </value>
            <value>
                <fullName>Itaú</fullName>
            </value>
            <value>
                <fullName>Santander</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DadosBancarios__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dados Bancários</relationshipLabel>
    <relationshipName>DadosBancarios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DadosBancarios__c/fields/NumeroConta__c.field-meta.xml
<CustomField>
    <fullName>NumeroConta__c</fullName>
    <label>Número da Conta</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DadosBancariosDAO.cls
public with sharing class DadosBancariosDAO {
    
    public static List<DadosBancarios__c> pegarContasPorDadoBancarios(Set<Id> setIdContas){
            return[
				SELECT 	Id,	Conta__c, Agencia__c, Ativo__c, NumeroConta__c FROM DadosBancarios__c WHERE Conta__c IN  :setIdContas
			];
    }

    public static List<DadosBancarios__c> pegarContaPorDadoBancarios(Id idAccount){
            return[
				SELECT 	Id,	Conta__c, Banco__c, Agencia__c, Ativo__c, NumeroConta__c FROM DadosBancarios__c WHERE Conta__c =  :idAccount
			];
    }

    public static List<DadosBancarios__c> pegarContasPorIdSomenteAtivos(Set<Id> setIdContasAtivadas){
            return [
                SELECT Id, Conta__c, Ativo__c FROM DadosBancarios__c WHERE Conta__c IN :setIdContasAtivadas AND Ativo__c = true
            ];
                                
    }

    public static List<DadosBancarios__c> pegarContasAtivosPorId(Set<Id> setIdContas){
            return [
                SELECT Id, Conta__c, Ativo__c FROM DadosBancarios__c WHERE Conta__c IN :setIdContas
            ];
    }

}