force-app/main/default/objects/Parcela__c/Parcela__c.object-meta.xml
<CustomObject>
    <label>Parcela</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Nome de Parcela</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcelas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Parcela__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <label>Apólice</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Parcelas</relationshipLabel>
    <relationshipName>Parcelas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AtualizarContrato.cls
public with sharing class AtualizarContrato {
    @future
    public static void ContarParcelas(Id idContrato){
        List<Parcela__c> lstNumeroParcelasPorContrato = [SELECT Id FROM Parcela__c WHERE Contrato__c =: idContrato];

        Contract contratoParatualizar = new Contract();
        contratoParatualizar.Id = idContrato;
        contratoParatualizar.NumeroParcelas__c = lstNumeroParcelasPorContrato.size();

        update contratoParatualizar;

    }

    public static void ChamarMetodoFeature(Id contrato){
        AtualizarContrato.ContarParcelas(contrato);
        System.debug('o Id de Contrato foi atualizado');
    }
}