force-app/main/default/objects/Parcela__c/Parcela__c.object-meta.xml
<CustomObject>
    <label>Parcela</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Nome de Parcela</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcelas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Parcela__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <label>Apólice</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Parcelas</relationshipLabel>
    <relationshipName>Parcelas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Parcela__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Paga</fullName>
            </value>
            <value>
                <fullName>Atrasada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ParcelaDAO.cls
public with sharing class ParcelaDAO {
    public static List<Parcela__c> buscarParcelasIdContrato(Id idContrato){
        return [
            SELECT Id FROM Parcela__c WHERE Contrato__c =: idContrato
        ];
    }

    public static List<Parcela__c> retornarParcelasVencidas(){
        List<Parcela__c> listaVencidas = [SELECT Id, DataVencimento__c FROM Parcela__c WHERE Status__c = 'Atrasada'];
    
        return listaVencidas;
    }

}